name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v4.2.2
       - name: Construção da imagem Docker
         uses: docker/build-push-action@v6.10.0
         with:
           context: ./src
           file: ./src/Dockerfile
           push: true
           tags: |
             welerson74/kube-news:v1
             welerson74/kube-news:latest
